version: '3.9'
services:
  db_pda_auth:
    container_name: pda_auth_db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - config/env/pda-auth-db.env
  pda_auth:
    build:
      dockerfile: pda-auth/Dockerfile
      context: .
    restart: unless-stopped
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - db_pda_auth
    env_file:
      - config/env/pda-auth.env
      
