version: '3.9'
services:
  db_pda_auth:
    container_name: pda_auth_db
    image: postgres
    ports:
      - "15432:5432"
    env_file:
      - config/env/pda-auth-db.env
  pda_auth:
    build:
      dockerfile: pda-auth/Dockerfile
      context: .
    restart: unless-stopped
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - db_pda_auth
    env_file:
      - config/env/pda-auth.env
  db_pda_order:
    container_name: pda_order_db
    image: postgres
    ports:
      - "25432:5432"
    env_file:
      - config/env/pda-order-db.env
  pda_order:
    build:
      dockerfile: pda-order/Dockerfile
      context: .
    restart: unless-stopped
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - db_pda_order
    env_file:
      - config/env/pda-order.env
  db_pda_delivery:
    container_name: pda_delivery_db
    image: postgres
    ports:
      - "35432:5432"
    env_file:
      - config/env/pda-delivery-db.env
  pda_delivery:
    build:
      dockerfile: pda-delivery/Dockerfile
      context: .
    restart: unless-stopped
    expose:
      - "8083"
    ports:
      - "8083:8083"
    depends_on:
      - db_pda_delivery
    env_file:
      - config/env/pda-delivery.env
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://0.0.0.0:29092,LISTENER_FRED://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    container_name: pda_kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    expose:
      - 9000
    depends_on:
      - broker
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKERCONNECT: broker:29092
