version: '3.9'
services:
  db_pda_auth:
    container_name: pda_auth_db
    image: postgres
    ports:
      - "15432:5432"
    env_file:
      - config/env/pda-auth-db.env
  pda_auth:
    build:
      dockerfile: pda-auth/Dockerfile
      context: .
    restart: unless-stopped
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - db_pda_auth
    env_file:
      - config/env/pda-auth.env
  db_pda_order:
    container_name: pda_order_db
    image: postgres
    ports:
      - "25432:5432"
    env_file:
      - config/env/pda-order-db.env
  pda_order:
    build:
      dockerfile: pda-order/Dockerfile
      context: .
    restart: unless-stopped
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - db_pda_order
    env_file:
      - config/env/pda-order.env    
