version: '3.9'
services:
  db_pda_auth:
    container_name: pda_auth_db
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - config/env/pda-auth-db.env
  pda-auth:
    container_name: pda_auth
    build:
      dockerfile: pda-auth/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      broker:
        condition: service_healthy
      db_pda_auth:
        condition: service_healthy
    env_file:
      - config/env/pda-auth.env
  db_pda_order:
    container_name: pda_order_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres
    env_file:
      - config/env/pda-order-db.env
  pda-order:
    container_name: pda_order
    build:
      dockerfile: pda-order/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      db_pda_order:
        condition: service_healthy
      broker:
        condition: service_healthy
    env_file:
      - config/env/pda-order.env
  db_pda_delivery:
    container_name: pda_delivery_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres
    env_file:
      - config/env/pda-delivery-db.env
  pda-delivery:
    container_name: pda_delivery
    build:
      dockerfile: pda-delivery/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      db_pda_delivery:
        condition: service_healthy
      broker:
        condition: service_healthy
    env_file:
      - config/env/pda-delivery.env
  pda_api_gateway:
    container_name: pda_api_gateway
    build:
      dockerfile: pda-api-gateway/Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "18080:8080"
    depends_on:
      pda-auth:
        condition: service_healthy
      pda-order:
        condition: service_healthy
      pda-delivery:
        condition: service_healthy
    env_file:
      - config/env/pda-api-gateway.env
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 29092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://:29092,LISTENER_FRED://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
