version: '3.9'
services:
  db_pda_auth:
    container_name: pda_auth_db
    image: postgres
    env_file:
      - config/env/pda-auth-db.env
  pda-auth:
    build:
      dockerfile: pda-auth/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      pda-delivery:
        condition: service_healthy
      broker:
        condition: service_started
      db_pda_auth:
        condition: service_started
    env_file:
      - config/env/pda-auth.env
  db_pda_order:
    container_name: pda_order_db
    image: postgres
    env_file:
      - config/env/pda-order-db.env
  pda-order:
    build:
      dockerfile: pda-order/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      pda-auth:
        condition: service_healthy
      db_pda_order:
        condition: service_started
      broker:
        condition: service_started
    env_file:
      - config/env/pda-order.env
  db_pda_delivery:
    container_name: pda_delivery_db
    image: postgres
    ports:
      - "35432:5432"
    healthcheck:
      disable: false
    env_file:
      - config/env/pda-delivery-db.env
  pda-delivery:
    build:
      dockerfile: pda-delivery/Dockerfile
      context: .
    restart: unless-stopped
    depends_on:
      db_pda_delivery:
        condition: service_started
      broker:
        condition: service_started
    env_file:
      - config/env/pda-delivery.env
  pda_api_gateway:
    build:
      dockerfile: pda-api-gateway/Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      pda-auth:
        condition: service_healthy
      pda-order:
        condition: service_healthy
      pda-delivery:
        condition: service_healthy
    env_file:
      - config/env/pda-api-gateway.env
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://0.0.0.0:29092,LISTENER_FRED://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
