application:
  users:
    - username: "jane@doe.com"
      password: "password123"
      firstName: "Jane"
      lastName: "Doe"
      role: ADMIN
    - username: "jack@doe.com"
      password: "password123"
      firstName: "Jack"
      lastName: "Doe"
      role: COURIER
    - username: "john@doe.com"
      password: "password123"
      firstName: "John"
      lastName: "Doe"
      role: USER
    - username: "root@user.su"
      password: "password123"
      firstName: "Root"
      lastName: "User"
      role: SUPERUSER
spring:
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
