application:
  users:
    - username: "jane@doe.com"
      password: "password123"
      firstName: "Jane"
      lastName: "Doe"
      role: ADMIN
    - username: "jack@doe.com"
      password: "password123"
      firstName: "Jack"
      lastName: "Doe"
      role: COURIER
    - username: "john@doe.com"
      password: "password123"
      firstName: "John"
      lastName: "Doe"
      role: USER
  security:
    jwt:
      provider:
        secretKey: 2A462D4A614E645267556B58703273357638782F413F4428472B4B6250655368
server:
  port: 8081
spring:
  application:
    name: pda-auth
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/pda_auth_db
    username: pda_auth_user
    password: pda_auth_pwd
    hikari:
      auto-commit: false
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: validate
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.format_sql: true
    open-in-view: false
  cloud:
    function:
      definition: ;
springdoc:
  swagger-ui:
    use-root-path: true
    with-credentials: true
    persist-authorization: true
  default-produces-media-type: application/json

