application:
  security:
    jwt:
      provider:
        secretKey: 2A462D4A614E645267556B58703273357638782F413F4428472B4B6250655368
server:
  port: 8083
spring:
  application:
    name: pda-delivery
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:35432/pda_delivery_db
    username: pda_delivery_user
    password: pda_delivery_pwd
    hikari:
      auto-commit: false
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: validate
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.format_sql: true
  jackson:
    deserialization:
      use-big-decimal-for-floats: true
  cloud:
    function:
      definition: courierUserCreatedConsumer;orderStatusChangedConsumer;orderCreatedProcessor
    stream:
      function:
        bindings:
          courierUserCreatedConsumer-in-0: userCreatedEvent
          orderStatusChangedConsumer-in-0: orderStatusChangedEvent
      bindings:
        #in
        orderCreatedProcessor-in-0:
          destination: order-created
          group: pda
        orderCreatedProcessor-out-0:
          destination: delivery-accepted
        orderStatusChangedEvent:
          destination: order-status-changed
          group: pda
        userCreatedEvent:
          destination: user-created
          group: pda
springdoc:
  swagger-ui:
    use-root-path: true
    with-credentials: true
    persist-authorization: true
  default-produces-media-type: application/json
