application:
  proxy:
    prefix: "/api"
    openApiUrl: /v3/api-docs
    microservices:
      auth:
        host: ${PDA_AUTH_HOST:localhost}
        port: ${PDA_AUTH_PORT:18081}
        endpoints:
          - /auth
      order:
        host: ${PDA_ORDER_HOST:localhost}
        port: ${PDA_ORDER_PORT:18082}
        endpoints:
          - /orders
      delivery:
        host: ${PDA_DELIVERY_HOST:localhost}
        port: ${PDA_DELIVERY_PORT:18083}
        endpoints:
          - /deliveries
          - /couriers

spring:
  application:
    name: pda-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[**]':
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods:
              - GET
              - PUT
              - OPTIONS
              - POST
springdoc:
  swagger-ui:
    enabled: false
